name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/setup-python@v3

      - name: Install Python 3.11.6
        uses: actions/setup-python@v3
        with:
          python-version:

      - name: Run tests with unittest
        run: python -m unittest
